### ISSUE TITLE
Question about cropping randomness

### ISSUE THREAD

**Issue by swordigo1995** [xmeng525/RealTimeDenoisingNeuralBilateralGrid#4]
Hello, 
       Thanks for your great work. I noticed that you sampling image crops in log space along w-axis during making the dataset (dataloader.py,  [line 203](https://github.com/xmeng525/RealTimeDenoisingNeuralBilateralGrid/blob/8281f8ec9c6d432fae3228edaa01b7d2f879ac8a/data_loader.py#L203)) . What's your motivation about this operation?

Looking forward to your reply.

**Comment by xmeng525** [comment]
Hi Haocheng,
You are right. The distribution of sampling image crops should be **uniform distribution**. 
The current dataLoader uses log-sampling because I was working on some small experiments and I forgot to change it back (I tried to [render in log-space](https://dl.acm.org/doi/10.1145/3203199) so I need to sample in log space).
Feel free to change the sampling back to uniform distribution! I will try to update the code in the future.
Please let me know if you have any other questions.
